# Java compiler command
JAVAC=javac

# JVM command
JAVA=java

# Path to ANTLR JAR
ANTLR_PATH := $(abspath libs/antlr-4.13.2-complete.jar)

# CLASSPATH configuration option for Java environment
CLASS_PATH_OPTION=-cp .:$(ANTLR_PATH)

# ANTLR compilation command configuration
ANTLR4=$(JAVA) -jar $(ANTLR_PATH)

# ANTLR test environment configuration
GRUN=$(JAVA) $(CLASS_PATH_OPTION) org.antlr.v4.gui.TestRig

# Grammar name
GRAMMAR_NAME=pascal_grammar

# Project paths (Makefile now at repository root)
SRC_DIR=src
GRAMMAR_FILE=$(SRC_DIR)/$(GRAMMAR_NAME).g

# Directory for generated files
GEN_PATH=$(SRC_DIR)/lexer

# Input file for run target converted to absolute path
RUN_FILE=$(abspath $(FILE))

# Run ANTLR and Java compiler
all: antlr javac
	@echo "Done."

# Run ANTLR to compile the grammar
antlr: $(GRAMMAR_FILE)
	cd $(SRC_DIR) && $(ANTLR4) -o lexer $(GRAMMAR_NAME).g

# Run javac to compile generated files
javac:
	$(JAVAC) $(CLASS_PATH_OPTION) $(GEN_PATH)/*.java

# Run the lexer. Command: $ make run FILE=path/to/source.pas
run:
	@if [ -z "$(FILE)" ]; then echo "Usage: make run FILE=path/to/source.pas"; exit 1; fi
	cd $(GEN_PATH) && $(GRUN) $(GRAMMAR_NAME) tokens -tokens $(RUN_FILE)

# Remove files generated by ANTLR
clean:
	@rm -rf $(GEN_PATH)

# Run automated tests
test:
	@./run-tests.sh

# Run automated negative tests
negative_test:
	@./run-negative-tests.sh

# Clean test result files
test-clean:
	@./run-tests.sh --clean
