# Java compiler command
JAVAC=javac

# JVM command
JAVA=java

# Path to ANTLR JAR
ANTLR_PATH := $(abspath libs/antlr-4.13.2-complete.jar)

# CLASSPATH configuration option for Java environment
CLASS_PATH_OPTION=-cp .:$(ANTLR_PATH)

# ANTLR compilation command configuration
ANTLR4=$(JAVA) -jar $(ANTLR_PATH)

# ANTLR test environment configuration
GRUN=$(JAVA) $(CLASS_PATH_OPTION) org.antlr.v4.gui.TestRig

# Grammars names
GRAMAR_NAME=Pascal
LEXER_NAME=$(GRAMAR_NAME)Lexer
PARSER_NAME=$(GRAMAR_NAME)Parser

# Project paths
SRC_DIR=src/
LEXER_FILE=$(SRC_DIR)$(LEXER_NAME).g
PARSER_FILE=$(SRC_DIR)$(PARSER_NAME).g

# Pascal Compiler Configuration
FPC = fpc
BIN_DIR = bin

# Directory for generated files
TARGET_PATH=$(SRC_DIR)/parser

# Input file for run target converted to absolute path
RUN_FILE=$(abspath $(FILE))

# Run ANTLR and Java compiler
all: antlr javac
	@echo "Done."

# Run ANTLR to compile the grammar
antlr: $(LEXER_FILE) $(PARSER_FILE)
	$(ANTLR4) -no-listener -visitor -o $(TARGET_PATH) $(LEXER_FILE) $(PARSER_FILE)

# Run javac to compile generated files
javac:
	@mkdir -p $(TARGET_PATH)
	$(JAVAC) $(CLASS_PATH_OPTION) $(TARGET_PATH)/*.java

# Remove files generated by ANTLR
clean:
	@rm -rf $(TARGET_PATH)
	@rm -rf $(BIN_DIR)


# Run the lexer
run-lexer:
	cd $(TARGET_PATH) && $(GRUN) $(LEXER_NAME) tokens -tokens $(RUN_FILE)

# Run the parser
run-parser:
	cd $(TARGET_PATH) && $(GRUN) $(GRAMAR_NAME) program $(RUN_FILE) -tree

# Run the parser with GUI
run-parser-gui:
	cd $(TARGET_PATH) && $(GRUN) $(GRAMAR_NAME) program $(RUN_FILE) -gui

# Run all automated tests
test:
	@chmod +x test.sh
	@./test.sh $(ARGS)

# Clean automated tests results
test-clean:
	@./test.sh --clean

# Compile and run the Pascal program
run-pascal:
	@mkdir -p $(BIN_DIR)
	$(FPC) -FE$(BIN_DIR) $(RUN_FILE)
	@echo "--- Executando o programa Pascal ---"
	@./$(BIN_DIR)/$$(basename $(RUN_FILE) .pas)